# Packet-Parser/Makefile
# sqm@hackers.pk


all		:
		make -C CExtensions/BPFCompiler -f makefile
		make -C CExtensions/BPFCompiler -f Makefile

clean		:
		make -C CExtensions/BPFCompiler -f Makefile clean
		rm -rf CExtensions/BPFCompiler/Makefile

